version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
    commands:
      - echo "Installing dependencies..."
      - mvn install

  pre_build:
    commands:
      - echo "Running pre-build steps..."
      - mvn clean

  build:
    commands:
      - echo "Building the application..."
      - mvn package

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Creating artifact..."
      - mv target/ICDIDesign-0.0.1-SNAPSHOT.jar application.jar

artifacts:
  files:
    - application.jar
  discard-paths: yes